create tab-navigator
ba-p/capp pull request #1
Opened 2022-07-06 10:05 UTC by lak2611

2022-07-12 14:11 UTC, ba-p commented
Chụp UI luôn nha @lak2611

2022-07-12 14:22 UTC, ba-p requested changes
Sửa lại

2022-07-12 14:22 UTC, ba-ppp commented on ui/app/App.tsx
> +import {NavigationContainer} from '@react-navigation/native';
Clean code

2022-07-12 14:22 UTC, ba-p commented on ui/app/App.tsx
> +                  style={{width: iconSize, height: iconSize}}
k được style `inline`

2022-07-21 18:09 UTC, lak2611 commented
![image](https://user-images.githubusercontent.com/44541211/180283862-3326314d-2572-46af-86a7-9989a24bfc85.png)

2022-07-29 12:18 UTC, closed without merging