Mobile/home screen
ba-p/capp pull request #2
Opened 2022-07-07 16:55 UTC by lak2611

2022-07-12 14:11 UTC, ba-ppp commented
chụp UI luôn nha @lak2611

2022-07-12 14:21 UTC, ba-p requested changes
Sửa lại

2022-07-12 14:21 UTC, ba-p commented on ui/app/App.tsx
> +            let iconSize = 30;
chỗ này viết style ở ngoài cho cả 2 luôn chứ k khai báo size 30 như v

2022-07-12 14:21 UTC, ba-p commented on ui/app/App.tsx
> +import {NavigationContainer} from '@react-navigation/native';
clean code lại { NavigationContainer } chứ đừng viết dính liền như v

2022-07-12 14:21 UTC, ba-p commented on ui/app/src/components/MyButton.tsx
> +      style={{
viết style ở ngoài 1 biến sẽ clean hơn là inline

2022-07-12 14:21 UTC, ba-p commented on ui/app/src/views/Camera/Camera.tsx
> +import {Text, View} from 'react-native';
Clean code

2022-07-12 14:21 UTC, ba-p commented on ui/app/src/views/Home/Home.tsx
> +import React, {useState} from 'react';
Clean code

2022-07-12 14:21 UTC, ba-p commented on ui/app/src/views/Home/Home.tsx
> +const Home = ({navigation}: any) => {
viết type đi đừng xài `any`

2022-07-12 14:21 UTC, ba-p commented on ui/app/src/views/Home/Home.tsx
> +  const [images, setImages] = useState<Array<any>>([]);
type lại

2022-07-12 14:21 UTC, ba-p commented on ui/app/src/views/Home/Home.tsx
> +      <Text style={{textAlign: 'center', fontSize: 30}}>
viết style ra ngoài

2022-07-12 14:21 UTC, ba-ppp commented on ui/app/src/views/Home/Home.tsx
> +              console.log({imageObject});
k được `console.log` nữa

2022-07-12 14:21 UTC, ba-ppp commented on ui/app/src/views/Home/Home.tsx
> +                    onPress={() => {
xài alert này xấu lắm, xài thư việt khác như là `react-hot-toast`

2022-07-21 18:29 UTC, lak2611 commented on ui/app/App.tsx
> +            let iconSize = 30;
này với cái dưới, sửa trong nhánh tab-navigator rồi, thì trong nhánh này không cần sửa luôn được không?

2022-07-21 18:50 UTC, lak2611 commented on ui/app/src/views/Home/Home.tsx
> +                    onPress={() => {
Này để test thôi à, nữa thêm chức năng vô rồi xóa

2022-07-21 18:53 UTC, lak2611 commented
> chụp UI luôn nha @lak2611

![image](https://user-images.githubusercontent.com/44541211/180293690-78a9bb19-2561-41f5-88fb-bdc73148171f.png)
![image](https://user-images.githubusercontent.com/44541211/180293836-386c316d-92f3-4e29-b8ae-eb9aca2fa0d5.png)
![image](https://user-images.githubusercontent.com/44541211/180293875-1e688dcb-5394-4b12-9362-ee64143f56f5.png)

2022-07-29 12:18 UTC, closed without merging